name: GitHub Actions Demo
on:  
  pull_request:
  push:
    branches:
      - master
  
jobs:
  example_matrix:
    strategy:
      fail-fast: false
      matrix:
        node: ["a","55"]
    runs-on: ubuntu-latest
    name: en nodo ${{matrix.node}}
    steps:
      - run: echo ${{matrix.node}}
