name: GitHub Actions Demo
on: [push]
jobs:


  example_matrix:
    strategy:
      fail-fast: false
      matrix:
        node: ["-a","asd"]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - run: mkdir ${{matrix.node}}
