name: GitHub Actions Demo
on:  
  pull_request:
  push:
    branches:
      - master
  
jobs:
  example_matrix:
    strategy:
      fail-fast: true
      matrix:
        node: ["a","n"]
    runs-on: ubuntu-latest
    name: en nodo ${{matrix.node}}
    steps:
      - run: echo ${{matrix.node}}





  j2:
    needs: example_matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo asd

