name: GitHub Actions Demo
on:  
  pull_request:
  push:
    branches:
      - master
  
jobs:
  example_matrix:
    runs-on: ["self-hosted","Linux"]
    container: ubuntu
    steps:
      - run: sleep 10
