name: GitHub Actions Demo
on:  
  pull_request:
  push:
    branches:
      - master
  
jobs:
  example_matrix:
    runs-on: ["self-hosted"]
    steps:
      - run: mkdir D:\prueba-action
      - run: mkdir c:\prueba-action
