name: GitHub Actions Demo
on: [push]
jobs:
  example_matrix:
    strategy:
      fail-fast: false
      matrix:
        node: ["-a","asd"]
        include:
          - continue: false
    continue-on-error: ${{ matrix.continue }}        
    runs-on: ubuntu-latest
    name: en nodo ${{matrix.node}}
    steps:
      - run: mkdir ${{matrix.node}}





  j2:
    needs: example_matrix
    runs-on: ubuntu-latest
    steps:
      - run: echo asd

